[package]
name = "my_rpg"
version = "0.1.0"
authors = ["Sean Rodman <srodman7689@gmail.com>"]
edition = "2018"

[dependencies]
specs = "0.14.0"

[dependencies.sdl2]
version = "0.32.2"
default-features = false
features = ["image", "ttf"]

